### ISSUE TITLE
Include ability to update Origin of user

### ISSUE THREAD

**Issue by mjseid** [cloudfoundry/cf-uaac#12]
As mentioned in this discussion on VCAP-DEV, please include the feature to update a users origin field in the offical uaac client.  This feature is necessary for those of us using multiple UAA origins where sometimes multiple accounts can get created.

https://groups.google.com/a/cloudfoundry.org/forum/#!topic/vcap-dev/I_Uo63ZFEs0

**Comment by sreetummidi** [comment]
@mjseid We plan on addressing this by disabling the Internal User Store and Creation of duplicate accounts. This feature will be available in the upcoming version of UAA. 
https://www.pivotaltracker.com/story/show/101791634
