### ISSUE TITLE
Missing parameter required_user_groups for client

### ISSUE THREAD

**Issue by cache-sk** [cloudfoundry/cf-uaac#126]
Cant set "required_user_groups" for client via `uaac client update [id]`, there is no such parameter as `--required_user_groups`.

Also, `uaac clients` and `uaac client get [id]` not showing required_user_groups at all, only result after update shows it.

Using `UAA client 4.17.0` installed / updated via gem.

**Comment by bruce-ricard** [comment]
This is a feature request.

The required_user_groups were [added to the UAA server](https://github.com/cloudfoundry/uaa/commit/597c664953a38862e5ccf53563b6506a30a866cc) in 2017. It was never added to the `uaac`.

Thank you for noticing that @cache-sk . We won't have the bandwidth to implement it. But if you really need it, and you are willing to implement it and send a PR, we'll be happy to review it and merge it.

**Comment by cache-sk** [comment]
@bruce-ricard Well, this is my first encounter with ruby, but i think i handled it.

**Comment by strehle** [comment]
reopen because we have a PR

**Comment by strehle** [comment]
@bruce-ricard @hsinn0 
Created also a PR where tests are , so fix is in https://github.com/cloudfoundry/cf-uaac/pull/127 and some test in my PR
