### ISSUE TITLE
Cannot target a context with capital letters

### ISSUE THREAD

**Issue by lefty27513** [cloudfoundry/cf-uaac#14]
If a UAA instance were deployed into a context root containing capital letters, the uaac command lower-cases the target URL and therefore cannot use this deployment.

This can be validated by adding the following to spec/common_spec.rb.
  it "maintains the capitalization of the target" do
    Cli.run("target example.com/UAA --force")
    Config.yaml.should include "https://example.com/UAA"
    Config.yaml.should_not include "https://example.com/uaa"
  end

On a real deployment, the 'uaac target' command asserts to succeed, and 'uaac contexts' shows me two contexts, but any other command (uaac users, uaac clients) complains that the target and context have not been set.

**Comment by cbguder** [comment]
@lefty27513 We have stopped active development on cf-uaac, and are planning to build a replacement for it. I will close this issue now.
