### ISSUE TITLE
Unclear documentation on how to install the command line client

### ISSUE THREAD

**Issue by muuhoffman** [cloudfoundry/cf-uaac#18]
Based on the documentation it seems that I need to build the gem, and then install it in order to run it.  However, after much confusion, I realized all I had to do was 'gem install cf-uaac'.  It would be nice if this was clearer in the README.

**Comment by dglozic** [comment]
I used 'gem install cf-uaac' on a MacBook Pro but uaac was not visible after that. What do I need to do to make it appear on my path?
