### ISSUE TITLE
uaac add client is interactive

### ISSUE THREAD

**Issue by sklevenz** [cloudfoundry/cf-uaac#19]
gem install cf-uaac -v 3.1.6 (currently latest version)

If you call
```
> uaac client add xyz [args] --secret abc
```
A interactive prompt is shown and client name (xyz) needs to be entered again. The flag --no-interactive has no effect. Previous version 3.1.5 does not show this behavior.

This prompt blocks any script execution for adding uaa clients.

**Comment by fhanik** [comment]
Can you specify all your arguments? Because if you are missing required parameters (like authorized_grant_types) it will switch to interactive.

**Comment by sreetummidi** [comment]
Available with UAA 3.2.0 and above
