### ISSUE TITLE
unable to use uaac target using ruby 2.x.x

### ISSUE THREAD

**Issue by nehagkalra** [cloudfoundry/cf-uaac#20]
$ gem install cf-uaac
$ uaac target uaa.cloudfoundry.com 
failed to access http://uaa.cloudfoundry.com: error: getaddrinfo: No such host is known.

**Comment by swetapatil** [comment]
I am facing same issue. what is solution for it?

**Comment by falcongi** [comment]
Any news regarding this issue?

**Comment by sreetummidi** [comment]
Please target your UAA install location
