### ISSUE TITLE
ERROR:  Error installing cf-uaac:  

### ISSUE THREAD

**Issue by nagamanikandank** [cloudfoundry/cf-uaac#21]
ERROR:  Error installing cf-uaac:
        The 'eventmachine' native gem requires installed build tools.

Can you please help to install uaac. I am getting above error

**Comment by sreetummidi** [comment]
@nagamanikandank Please provide more information about the environment where you are trying to install the gem

**Comment by shatrupapatil** [comment]
@nagamanikandank  we faced same issue Please guide to us if you problem is solved .
