### ISSUE TITLE
get token failed on cf-v236

### ISSUE THREAD

**Issue by ihocho** [cloudfoundry/cf-uaac#23]
using uaac, i tried to get token but i got this error.
```
$ uaac token get
Email:  admin
Password:  *****

CF::UAA::BadResponse: status 200

attempt to get token failed
```

I don't know what problem is. Let me know how to fix it.

**Comment by mbhave** [comment]
@ihocho the uaac token get uses the cf client in order to get a token via implicit grant type. The cf client no longer has the implicit grant type. You can get a token for the user using password grant. 
```
uaac token owner get 
```
