### ISSUE TITLE
add ability to specify target in ENV

### ISSUE THREAD

**Issue by erjoalgo** [cloudfoundry/cf-uaac#27]
multiple scripts attempting uaac commands against multiple targets currently must share the same `~/.uaac.yml` and might fail if they conflict with each other. This is a feature request to add a UAAC_HOME similar to [CF_HOME](http://docs.cloudfoundry.org/cf-cli/getting-started.html)

`By default, config.json is located in your ~/.cf directory. The CF_HOME environment variable allows you to locate the config.json file wherever you like.`

**Comment by erjoalgo** [comment]
Closing since there is the `--config` flag which allows changing the default config file.

**Comment by drennalls** [comment]
I agree. It would be alot easier to automate things where you need to switch between different environments (especially with different UAAs or ID zones) by just setting a `UAAC_HOME`. https://www.pivotaltracker.com/story/show/125756991 mentions allowing for this in the (still experimental) go cli https://github.com/cloudfoundry-incubator/uaa-cli
Is there no chance of adding this to the ruby gem in the interim ?

**Comment by mamacdon** [comment]
@drennalls Support for `UAAC_HOME` has been [added](https://github.com/cloudfoundry/cf-uaac/pull/61), although it doesn't appear to have made it into a release yet.
