### ISSUE TITLE
CF-UAAC not establishing TLS1.2, only TLS1.0

### ISSUE THREAD

**Issue by jmckeown** [cloudfoundry/cf-uaac#28]
My setup is: OSX 10.10 / Ruby 2.3.1p112 / OpenSSL 1.0.2h

The server I am communicating with supports only TLS1.2 and I am manually able to establish a connection with the server using the openssl client using TLS 1.2.  However, any requests I have made using cf-uaac only attempt to establish TLS 1.0 connections and the handshake fails due to the server not supporting anything less than TLS 1.2.  I am confirming the request for TLS 1.0 in Wireshark.  Uaac works fine from my windows machines, but both OSX machines have the same issue.  

I pulled the source for the project and attempted to modify lib/uaa/cli/curl.rb by adding the following at line 65, before http.use_ssl=true and recompiled, but it did not resolve the issue.  Any help is appreciated.

```
ctx = OpenSSL::SSL::SSLContext.new
ctx.ssl_version = :TLSv1_2
```

**Comment by jmckeown** [comment]
Any thoughts?

**Comment by jmckeown** [comment]
It turns out that the uaac script provided by the cf-uaac gem includes a shebang header that specifies the default OSX ruby installation. I discovered this by modifying the cf-uaac source code to print the ruby version used when UAAC is running, and it turned out to be different than what was in my path or /usr/bin/ruby. The default installation on OSX 10.10 (Yosemite) is 2.0.0 and it does not support TLS1.2.

I resolved this by modifying the UAAC installed script at /usr/bin/uaac to replace this line:

 #!/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
with this line:

 #!/usr/bin/ruby

**Comment by d** [comment]
Hi Jeremy,
Please note that `cf-uaac` gem does NOT include specific system dependent shebang lines. Shebang lines are generated by Rubygems when you do `gem install`. The solution is *not* to manually edit the shebang line, but instead, to `gem install` the `cf-uaac` gem under a Ruby version that supports the desired TLS version.

Jesse
