### ISSUE TITLE
Incomplete help output for deleting users

### ISSUE THREAD

**Issue by henrytk** [cloudfoundry/cf-uaac#29]
When running `uaac -h` the guidance says the command for deleting a user is 'user delete [name]'. However, when running `uaac users` the name field is often blank, or contains objects of data (such as familyname et cetera). I successfully deleted a user by passing the value contained in `username`. 

The help output should read 'user delete [username]', if that is the correct usage, or 'user delete [username|name]' if both are allowed.

**Comment by combor** [comment]
Hi @sreetummidi, why this was closed without any info? Pivotal story is also not updated.
