### ISSUE TITLE
--skip-ssl-validation is not working

### ISSUE THREAD

**Issue by tgreenyc** [cloudfoundry/cf-uaac#30]
when using uaac target, the --skip-ssl-validation argument doesn't seem to do anything:

`uaac target https://localhost:8080 --skip-ssl-validation`

failed to access https://localhost:8080: Invalid SSL Cert for https://localhost:8080/login. Use '--skip-ssl-validation' to continue with an insecure target

**Comment by sreetummidi** [comment]
Please refer to steps here : https://github.com/cloudfoundry/uaa-release on how to configure UAA with SSL. 8080 is a non ssl port

**Comment by HerrmannHinz** [comment]
any progress on this one? 
still not fixed for me:

`hinztobi@cin-mbpro-26  ~  sw_vers                                                                                                                                                                                  1 ↵  452  11:26:24
ProductName:	Mac OS X
ProductVersion:	10.12.4
BuildVersion:	16E195
 hinztobi@cin-mbpro-26  ~  uaac --version                                                                                                                                                                             ✓  453  11:26:25
UAA client 3.12.0
 user@mashine  ~  uaac target https://opsmanager.xxx.xxx.xxx.xxxx-xxxx.xxx.de/uaa --skip-ssl-validation                                                                                            ✓  454  11:26:31
failed to access https://opsmanager.xxx.xxx.xxx.xxxx-xxxx.xxx.de/uaa: Invalid SSL Cert for https://opsmanager.dev.api.oneweb.mercedes-benz.cinteo.de/uaa/login. Use '--skip-ssl-validation' to continue with an insecure target`

**Comment by james-fitzgerald** [comment]
Looks like it got closed prematurely because the original example included port 8080. I will re-raise the issue.
