### ISSUE TITLE
Write request body to a file for GET 

### ISSUE THREAD

**Issue by mehrotra-prateek** [cloudfoundry/cf-uaac#31]
Hello,
I am trying to get the request body into a file using uaac curl running command 

```
uaac curl https://cf-ops-mgmt.com/api/installation_settings -X GET -k -d /tmp/request_body.txt
```

I don't get the desired result in the file whilst I can see the output on screen. Please advise

**Comment by sreetummidi** [comment]
We don't have plans to support this. Please use regular curl and provide the token in the authorization header
