### ISSUE TITLE
member add command destroys group to group mappings

### ISSUE THREAD

**Issue by milenmanov** [cloudfoundry/cf-uaac#36]
Hi,
 I have a group that has a member - another group.
If I use the member add command to add a user the group to group mapping is lost.

Tested with UAA client 3.5.0

**Comment by Essenpreis** [comment]
See https://cloudfoundry.slack.com/archives/C03FXANBV/p1493927873369874 for a workaround until bug is fixed.

**Comment by cbguder** [comment]
This is fixed in the latest version of UAAC (3.13.1).
