### ISSUE TITLE
execution expired

### ISSUE THREAD

**Issue by prasadpete** [cloudfoundry/cf-uaac#38]
I get below when I do a `uaac target`.

```
$ uaac target https://opsmanagerurl/uaa --skip-ssl-validation
failed to access https://opsmanagerurl/uaa: execution expired
```
`ping `and `telnet  `on 443 to opsmanagerurl works fine from source. Any other parameter that I need to verify?

**Comment by sreetummidi** [comment]
Are you able to access UAA in the browser. Is the login page loading?

**Comment by prasadpete** [comment]
Hi @sreetummidi - Yes, UAA page is loading fine and I'm able login to the ops manager.

**Comment by sreetummidi** [comment]
can you try curl -k 'https://opsmanagerurl/uaa/info' -H 'Accept: application/json'

Does it return UAA info

**Comment by prasadpete** [comment]
got `curl: (56) Received HTTP code 503 from proxy after CONNECT` response.

**Comment by vaibhav259** [comment]
I'm running into the same issue. uaac token owner gets expired and "curl -k 'https://opsmanagerurl/uaa/info' -H 'Accept: application/json'" give me uaa info.
![image](https://user-images.githubusercontent.com/22019603/170409704-fb6d0898-a8fa-46ae-9b89-19051fcb6eb5.png)
