### ISSUE TITLE
~/uaac.yml should not get created world-readable

### ISSUE THREAD

**Issue by devoteam-dr** [cloudfoundry/cf-uaac#42]
a) either warn the user about the world-readable fact - and LOUDLY 
b) or don't rely on the current umask and always create the file 600

I installed uaac (today) with `gem install cf-uaac`

Thanks.

**Comment by jhamon** [comment]
This seems like an important issue but is unlikely to be prioritized by our team soon. We would accept a pull request that fixes this problem. @devoteam-dr

**Comment by tnwang** [comment]
Fixed.
