### ISSUE TITLE
Gem fails to install on stock Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by cnelson** [cloudfoundry/cf-uaac#44]
This gem fails to install on Ubuntu 14.04 with the message:

```
Fetching: public_suffix-3.0.0.gem (100%)
ERROR:  Error installing cf-uaac:
	public_suffix requires Ruby version >= 2.1.
```
I believe this is due to [addressable bumping to public_suffix 3.0 ](https://github.com/sporkmonger/addressable/commit/6f0263633be4144052c276a770d663d51dccb26d#diff-76a9e5bbb0f907a004d60b3a55b1460a) which requires a newer version of ruby than 14.04 ships.  Addressable is pulled in as a dependency of [em-http-request](https://github.com/cloudfoundry/cf-uaac/blob/master/cf-uaac.gemspec#L46)

This can be worked around by manually installing an earlier version of public_suffix with `gem install public_suffix -v '<3.0'` before running `gem install cf-uaac`

**Comment by sreetummidi** [comment]
UAAC in maintenance mode. Only critical fixes will be done
