### ISSUE TITLE
`uaac clients` output is unfriendly to shell scripting

### ISSUE THREAD

**Issue by 46bit** [cloudfoundry/cf-uaac#46]
The `uaac clients` command gives output that's almost, but not quite, valid YAML. It has two leading spaces, and there are no colons after the client names:

```sh
$ uaac clients
  admin
    scope: uaa.none
    resource_ids: none
    authorized_grant_types: client_credentials
    autoapprove:
    authorities: clients.read password.write clients.secret clients.write
        uaa.admin scim.write scim.read
    lastmodified: 1713602432872
[...]
```

That this isn't valid YAML is perfectly acceptable. But it's quite hard to work with it in any automated way: I haven't been able to get the `-a` option to output a list of client names (I've tried `-a name` and many other variations.)

**Comment by tnwang** [comment]
Thanks for this input. UAAC clients does indeed seem to have an issue filtering by `client_id`. The closest I'm able to get is `uaac curl -k /oauth/clients`, which returns a JSON of client configurations. On command line I can do `uaac curl -k /oauth/clients | grep client_id` to get a full list of client IDs.

UAAC is in maintenance mode and no new features will be added at this time. We have considered a --json option to help with automation, and will likely consider that for the future https://github.com/cloudfoundry-incubator/uaa-cli.

Regards,

Tian
