### ISSUE TITLE
Is there an easy way to get a client token into a script (and save grep and cuts)

### ISSUE THREAD

**Issue by haydonryan** [cloudfoundry/cf-uaac#47]
Just wondering if there is a better way to return the token (or an improvement that could be made to  the cli to make this easie )

```
uaac target $URL/uaa --skip-ssl-validation
uaac token owner get opsman user -s "" -p password
apitoken=`uaac contexts | grep access_token | cut -d ':' -f  2 | cut -d ' ' -f 2` 
```

Thanks :)

**Comment by jhamon** [comment]
I'm going to save this snippet for my own use. The problem of ridiculous output formats from uaac is well known. 🙈 

We have an [experimental cli](https://github.com/cloudfoundry-incubator/uaa-cli) rewrite in progress that aims to output standard json that you could slice and dice with jq or other tools, but it's not yet at feature parity with the UAA so we haven't made any official releases of it.
