### ISSUE TITLE
uaac does not apply env var https_proxy to https targets (but http_proxy)

### ISSUE THREAD

**Issue by heikoettelbruecksap** [cloudfoundry/cf-uaac#49]
Following the typical convention for environment variables for proxy servers on Linux, and with UAA being available on an HTTPS URL, I set https_proxy to the respective proxy server URL. Still I realized the connection from uaac to UAA failed, and looking at network traffic, I realized it's because uaac still tried to connect *directly* to UAA, not via the proxy.
Trying to set http_proxy to the same value finally made the connection work, so it seems like uaac does support proxies, but always expects the proxy to be configured in http_proxy, regardless of whether the target is an HTTP or HTTPS URL.
From my point of view, it would be good to follow the usual conventions and evaluate either one or the other environment variable depending on the protocol of the target URL. Maybe you can have a fallback to keep compatibility by choosing http_proxy if https_proxy is not set.

**Comment by sreetummidi** [comment]
@heikoettelbruecksap We don't have plans to add this support to UAAC at this time. UAA supports server side proxy set up using the same env variables
