### ISSUE TITLE
Can uaac connect thru SOCKS5 tunnel?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/cf-uaac#51]
Recently https://github.com/cloudfoundry-incubator/credhub-cli/releases/tag/1.6.0 added support for "short-lived socks5 proxy over SSH" via `$CREDHUB_PROXY` variable; and the `bosh` supports it via `$BOSH_ALL_PROXY`. Can the `uaac` CLI connect to a UAA server via a SOCKS5 tunnel?

**Comment by DennisDenuto** [comment]
@drnic It looks like `cf-uaac` does not support connecting via SOCKS5. The uaa team is currently only working on bug fixes and patching any vulnerabilities.

However, we will review and accept PRs.
