### ISSUE TITLE
Stopping and Starting AWS instances in cloudfoundry

### ISSUE THREAD

**Issue by wilfredwilly** [cloudfoundry/cf-uaac#56]
Hi All,

Good Day :)

I have deployed bosh components on AWS. Need procedure  to stop the AWS instances when i am not using the cloud foundry environment 
Please help me out.

**Comment by DennisDenuto** [comment]
Thanks for creating this issue. Closing as this issue belongs in github.com/cloudfoundry/bosh/issues

This repo pertains to a  CLI tool for the [uaa](github.com/cloudfoundry/uaa)
