### ISSUE TITLE
uaac subcommand output is not valid yaml

### ISSUE THREAD

**Issue by BrandonStiff** [cloudfoundry/cf-uaac#57]
I've noticed several of the uaac subcommands output yaml-like output, that isn't quite valid yaml output.  For instance:

```
uaac users
```

Outputs (in part):

>   -                                               
>     id: 2585a8f1-ffbf-4667-b612-13b51894ec3d      
>     meta                                          
>       version: 0                                  
>       created: 2018-04-17T21:08:31.000Z           
>       lastmodified: 2018-04-17T21:08:31.000Z      
>     name                                          
>     emails:                                       
>     -                                             
>       value: bsti@plex.com                        
>       primary: false                              
>     groups:                                       
>     -                                             

The "meta" and "name" elements are missing the colons at the end.  There are similar issues with uaac clients and uaac groups.

It would be very helpful to have the output be valid yaml that could be parsed and consumed by other applications.  

I'm running uaac:
UAA client 4.1.0

On Windows 10 with Ruby version:
ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]

Any questions or further data I can provide, please let me know!

**Comment by jhamon** [comment]
This is a known issue and unlikely to be fixed in the `uaac`. We're planning to rewrite the UAA cli [in go](https://github.com/cloudfoundry-incubator/uaa-cli) and one of the explicit goals is for outputs to be machine-parseable.
