### ISSUE TITLE
Misleading documentation in `uaac user update`

### ISSUE THREAD

**Issue by keymon** [cloudfoundry/cf-uaac#58]
The help of `uaac user update`:

```
$ uaac user update -h

  user update [name]               Update a user account with specified options
                                   --given_name <name>
                                   --family_name <name>
                                   --emails <addresses>
                                   --phones <phone_numbers>
                                   --origin <identity provider origin, defaults to UAA>
                                   --del_attrs <attr_names>, list of attributes to delete

```

But the ` --origin`  option refers to which user to update if there are multiple users with different origin. It does not mean that you can update the origin!

I think this is misleading and it should be reworded.

**Comment by wc22222** [comment]
Good suggestion, @keymon. Tagging sap-dojo as well. @tack-sap

**Comment by strehle** [comment]
can you please rebase your contribution, then we can accept it - thanks

**Comment by keymon** [comment]
This was done 3 years ago, I do not even work with this tech anymore. I will rebase this, but not test it whatsover

**Comment by keymon** [comment]
I rebased. I am missing some authorization or something :shrug:
