### ISSUE TITLE
misleading error when ca-cert file does not exists

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry/cf-uaac#60]
when targeting the uaa `uaac` uses the path of the file instead of reading the content into `~/uaac.yml`
like fly, bosh does.

so if the ca-cert file get removed for some reason.
it prints out the following error
`OpenSSL::X509::StoreError: system lib`

my suggestion that it would use the same flow as fly and bosh
and pasting the content of the file in uaac.yml
```
---
https://10.0.0.6:8443:
    ca_cert: |+
      -----BEGIN CERTIFICATE-----
      MIIEEzCCAnugAwIBAgIQUogop3FnL270iATtUG75FzANBgkqhkiG9w0BAQsFADAz
      -----END CERTIFICATE-----
```
instead of the current way
```
---
https://10.0.0.6:8443:
  ca_cert: "/tmp/tmp.cmQZShIPbU/ca.pem"
````

**Comment by DennisDenuto** [comment]
Thanks for creating this issue. UAAC is in maintenance mode and no changes are being made at this time. We're planning to rewrite the [UAA cli in go](https://github.com/cloudfoundry-incubator/uaa-cli). I think it makes sense to follow what `bosh` and `fly` does in relation to storing `ca certs` when we re-write to go.

We will however review / merge PRs.
