### ISSUE TITLE
Add bracket spacing to passcode url

### ISSUE THREAD

**Issue by azerella** [cloudfoundry/cf-uaac#62]
When generating a SSO passcode using `uaac` the passcode URL is attached to a `)` When the user clicks this url, it navigates to `https://<config>/passcode)`, **not** `https://<config>/passcode`. Leading to a error page
 
### Reference 
<img width="598" alt="screen shot 2018-07-23 at 2 04 06 pm" src="https://user-images.githubusercontent.com/1501560/43056752-5094e400-8e81-11e8-8920-a4ef0ae7288f.png">

### Error
![image](https://user-images.githubusercontent.com/1501560/43056852-f7319f1a-8e81-11e8-9607-eebe3a390884.png)

**Comment by drnic** [comment]
Perhaps try the new https://github.com/cloudfoundry-incubator/uaa-cli which is more actively developed than this older cli

**Comment by strehle** [comment]
is this sill valid with latest cf-uaac?
