### ISSUE TITLE
`uaac client update --refresh_token_validity X` where X is too big

### ISSUE THREAD

**Issue by sphawley** [cloudfoundry/cf-uaac#65]
When updating a client with `uaac client update --refresh_token_validity X` where 2147483648 > X > 536870911 (ie: has 30 or 31 bits), 
the cli does not throw an error. However, when creating an access token from this refresh token we get the following error: `{"error":"server_error","error_description":"java.lang.Long cannot be cast to java.lang.Integer"}`

There were two behaviors here that we wanted to bring to your attention:
1) That a raw java error is returned
2) That the uaac client accepts integers for refresh/access token timeouts that cause errors when tokens are generated.

These errors are probably not very urgent to fix, but might be worth pursuing if they are easy and quick to solve.  Thanks!

**Comment by bruce-ricard** [comment]
This error was fixed on the UAA server a little while ago. Since the error message you showed says `server_error`, I'm going to guess that there is no issue on the CLI side.
