### ISSUE TITLE
Long-term vision of `cf-uaac` with `uaa-cli`?

### ISSUE THREAD

**Issue by aegershman** [cloudfoundry/cf-uaac#67]
Are there any plans to "officially" replace the ruby-based `cf-uaac` with the [go-based `uaa-cli`?](https://github.com/cloudfoundry-incubator/uaa-cli) Just curious if there is a "vision" for one or the other to be referenced in doc, packaged in scripts, used by people day-to-day, etc.

I apologize I hope this isn't a silly question to begin with

**Comment by wc22222** [comment]
@aegershman, thanks for the question. UAA go based CLI is on our existing UAA roadmap, it's just not the highest priority for this moment, we plan to have feature parity with the ruby based UAAC cli to simplify and improve the platform operator user experience.
