### ISSUE TITLE
-bash: uaac: command not found

### ISSUE THREAD

**Issue by navin205** [cloudfoundry/cf-uaac#68]
Hi Team, I am planning to deploy autoscaling on an existing opensource cloudfoundry. As a prerequisite i install cf-uaac by 
# gem install cf-uaac
i got a prompt saying successfull, but i get an error while targetting, screenshot attached.

![image](https://user-images.githubusercontent.com/40890613/56032385-b3a88780-5d3f-11e9-9161-9c954a0e6f51.png)

Can you please assist why i am getting as uaac command not found even after installing cf-uaac. could not find any solution on google.

**Comment by navin205** [comment]
Updating further while i install cf-uaac using gem install cf-uaac i get below error 
![image](https://user-images.githubusercontent.com/40890613/56035270-56183900-5d47-11e9-9338-366fcf48acd8.png)
![image](https://user-images.githubusercontent.com/40890613/56035312-70521700-5d47-11e9-811f-c1ef90fba153.png)

**Comment by strehle** [comment]
is this sill valid with latest cf-uaac

**Comment by bgandon** [comment]
I've submitted possible documentation improvement in PR #108.

**Comment by strehle** [comment]
@bgandon Thanks again https://github.com/cloudfoundry/cf-uaac/pull/108
