### ISSUE TITLE
cf-uaac failing for "gem install cf-uaac"

### ISSUE THREAD

**Issue by sajithakak** [cloudfoundry/cf-uaac#82]
The same used to work till last week

Now :
Building native extensions.  This could take a while...
ERROR:  Error installing cf-uaac:
	launchy requires Ruby version >= 2.4.0.
Successfully installed eventmachine-1.2.7
Successfully installed public_suffix-4.0.3
Successfully installed addressable-2.7.0
ERROR: Job failed: exit code 1

======

Before:
Building native extensions.  This could take a while...
Successfully installed eventmachine-1.2.7
Successfully installed public_suffix-4.0.3
Successfully installed addressable-2.7.0
Successfully installed launchy-2.4.3

Any help is appreciated. thanks.

**Comment by sajithakak** [comment]
the only change I could see is https://rubygems.org/gems/launchy/versions/2.5.0 
Launchy had a new version 2.5.0 released on 28th Feb and we also observed things failing since then.

**Comment by sajithakak** [comment]
Updated ruby to 2.5.1 to enable launchy (since the new version update to 2.5.0).

**Comment by copiousfreetime** [comment]
The version 2.5 relesae of launchy updated the minimum required version of ruby to be 2.4 - which is the current lowest supported ruby. If this update of the minimum ruby version for launchy causes other issues for cf-uaac - please let me know and I'll do a release of launchy to drop the minimum ruby version to the lowest supported version necessary to be compatible with cf-uaac.  Thanks.

**Comment by strehle** [comment]
newer ruby needed
