### ISSUE TITLE
How to obtain access token with client certificate or how to inject token?

### ISSUE THREAD

**Issue by nenaraab** [cloudfoundry/cf-uaac#91]
Hi,

when using `uaac token client get` as part of ci-cd script as described [here](https://docs.cloudfoundry.org/concepts/architecture/uaa.html) to retrieve a token using client credentials, how to do the same using a client certificate?

Are you going to support mtls based communication to fetch an access token? 
Or do you offer an option to inject an access token to your context, and if yes, how?

Thanks in advance,
Nena

**Comment by strehle** [comment]
HI @nenaraab ,
here is an example
https://github.com/cloudfoundry/cf-uaac/blob/master/curl_auth.sh
-> uaac context | awk '/^ *access_token\: *([a-zA-Z0-9.\/+\-_]+) *$/ {print $2}' -
returns currend used token

**Comment by strehle** [comment]
uaac is mainly for uaa in CF and this currently does not provide mTLS, e.g. https://github.com/cloudfoundry/uaa/issues/1459
